import { resolve } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { doors, serves } from 'kehikot-module-protocol/serve'
import { defineConfig } from 'vite'

import { BUILD, MANIFEST, TICKET, answer, stream } from './doors.ts'
import { ID, PREFERRED_PORT } from './manifest.ts'

/**
 * - `serves()` first: it claims the port from PREFERRED_PORT (or $PORT from a host) and keeps the
 *   registration true. So no `server.port` here.
 * - `doors()` serves everything that is not a source file from this one process: the manifest, the
 *   page at `/app` (and `/print`, the same document on a route of its own) with the write ticket
 *   and the build printed into it, the two server-sent-event doors through `stream`, and
 *   `/healthz`, `/mcp` and `/api/*` through `answer`. A module is ONE ORIGIN; see the protocol's
 *   docs/module-plumbing.md.
 * - No `server.cors`: the manifest declares storage, so the page is same-origin and a permissive
 *   CORS header would only let strangers read the ticket.
 * - No alias for `kehikot-module-protocol`: resolve it through its exports, as the host does. The
 *   `@` alias points inside this repo, for shadcn.
 * - No build: the page is generated by `doors()`.
 * - `base: './'`, because a host frames this at whatever address it wrote down.
 */
export default defineConfig({
  base: './',
  plugins: [
    serves({ id: ID, prefer: PREFERRED_PORT }),
    doors({ manifest: MANIFEST, answer, stream, build: BUILD, page: { title: 'Slides', ticket: TICKET }, pages: ['/print'] }),
    react(),
    tailwindcss(),
  ],
  resolve: { alias: { '@': resolve(import.meta.dirname, 'src') } },
})
